### ISSUE TITLE
请问下如何获取群消息

### ISSUE THREAD

**Issue by aliyuchang33** [richardchien/nonebot#101]
如题，文档中只有on_command 和 on_request装饰器的用法，进阶文档甚至没写全所有装饰器，那么我该如何获取普通的群消息呢？ 用on_command获取么？

**Comment by richardchien** [comment]
on_command 可以处理群消息的，只不过默认情况下需要 at 它，可以给 on_command 传入 only_to_me=False
参数，这就不需要 at 了，其他和私聊完全一致

Hork <notifications@github.com> 于 2019年10月12日周六 23:42写道：

**Comment by aliyuchang33** [comment]
好的，谢谢

**Comment by aliyuchang33** [comment]
额，我的意思是，不是以命令的形式，而是普通聊天，如何获取呢？如果不指定命令，他好像就直接过滤了

**Comment by momocow** [comment]
@aliyuchang33 建議去看看 nonebot 的 [NLP](https://nonebot.cqp.moe/guide/nl-processor.html)。
再不然就是使用底層 aiocqhttp 的 on_message。

**Comment by richardchien** [comment]
> 再不然就是使用底層 aiocqhttp 的 on_message。

@aliyuchang33 用底层的 aiocqhttp 的 `on_message` 不代表需要真的去用 aiocqhttp，nonebot 的 bot 对象本身就是个 aiocqhttp 的 `CQHttp` 对象，完全一样用就可以
