### ISSUE TITLE
没有匹配command的消息，可以有默认答复吗？

### ISSUE THREAD

**Issue by abaity** [richardchien/nonebot#110]
没有匹配command的消息，可以有默认答复吗？看文档好像说command装饰器不支持类似通配符的概念，但这个需求应该很常见，所以应该是有方法的。请各位大神帮忙。

**Comment by richardchien** [comment]
用一个返回 confidence 为 60 的自然语言处理器就可以了，例如
https://github.com/cczu-osa/aki/blob/bae28c59db683c6c66c3fdaeb0048f1d1b12b824/aki/plugins/tuling/__init__.py#L90

abaity <notifications@github.com>于2019年12月1日 周日23:43写道：

**Comment by abaity** [comment]
谢大佬，问题搞定。
