### ISSUE TITLE
一个NoneBot如何做到支持多个CQ反向链接？

### ISSUE THREAD

**Issue by abaity** [richardchien/nonebot#111]
大佬，如何让nonebot支持多个CQ链接到并正常工作？文档上面没找到相关说明。正常来说，这也是个很常见的需求，要不然nonebot和其他的普通插件就没有区别了。

**Comment by ExerciseBook** [comment]
@abaity 我寻思着nonebot本身就支持这个吧。有注解是用来限定QQ号那就意味着也有方法多连接。

**Comment by ExerciseBook** [comment]
@ExerciseBook 把cqhttp的配置复制几份应该就🉑️

**Comment by richardchien** [comment]
@abaity 就像配置一个 CQ 一样配置多个 CQ，NoneBot 会自动判断来源 QQ

**Comment by wjllance** [comment]
https://aiocqhttp.cqp.moe/#/what-happened#cqhttp-%E7%B1%BB

在用scheduler的时候，会有这个疑问，这个时候没有event，bot的消息如何发送给指定的一个ws连接

**Comment by richardchien** [comment]
调用 api 时加上 self_id 参数

Lance <notifications@github.com> 于 2020年7月6日周一 16:47写道：
