### ISSUE TITLE
是否有多线程执行不同插件的思路和实例

### ISSUE THREAD

**Issue by the-Miu** [richardchien/nonebot#117]
在开发插件的时候，我需要做一个每隔1分钟运行一次的定时插件。该插件是独立的，不需要与其他插件配合。囿于运行效率问题，每次运行都需要10秒左右才能完成该插件指令，在此期间其他插件的任何功能都没办法即时使用。
因此我考虑将插件设计成多线程的形式，但是我以前没用这个插件做过这个，没有一个具体的思路，通过谷歌也仅查到了一些非nonebot的多线程实现方式，不知道如何应用到nonebot里。
恕本人愚钝，请问能否提供一下具体的思路？如果有实例的话是最好不过的。
当然如果有其他的替代方案也烦请指点一下，感激不尽！
稍微有点伸手党的感觉，但是我确实没有其他办法了，望海涵！

**Comment by yuudi** [comment]
nonebot是协程的，要么把插件写成协程，要么新建一个线程然后用协程来管理。

取决于你的耗时步骤能不能做成协程。

**Comment by richardchien** [comment]
如果是 10 秒的 I/O 操作，那就看看能不能用支持 asyncio 的网络请求库（如 aiohttp、httpx）、文件操作库（如 aiofile）、数据库访问库（如 aiosqlite、asyncpg、gino）来替换；如果是 10 秒的 CPU 密集性操作，应该使用多进程，见 https://docs.python.org/3/library/multiprocessing.html

**Comment by the-Miu** [comment]
@yuudi @richardchien 感谢两位的解答，目前采用了异步+多进程混合的方式解决了
