### ISSUE TITLE
可以取得请求加群者的基本信息或是加群备注信息

### ISSUE THREAD

**Issue by mkdir700** [richardchien/nonebot#119]
广告小号太多，想取出加群者的基本信息，比如Q龄，进行判断，再觉得是否同意入群

**Comment by ExerciseBook** [comment]
加群者基本信息：获取陌生人信息
加群备注信息：在加群上报事件里有

哦 nonebot 啊。我不知道（

**Comment by ExerciseBook** [comment]
@ExerciseBook nonebot本身也是基于cqhttp跑的，你也照样可以用cqhttp里的挨批

**Comment by richardchien** [comment]
可以去 https://cqhttp.cc/docs/#/API 找一找有没有合适的 API 来获取你要的信息，不过 Q龄 目前应该是没有直接的接口能获取的
