### ISSUE TITLE
只能响应数字和字母，有汉字就不会响应，但是日志里确实发送出消息了，QQ里看不见

### ISSUE THREAD

**Issue by Campanulata** [richardchien/nonebot#120]
from nonebot import on_command, CommandSession
from nonebot import on_natural_language, NLPSession, IntentCommand
from nonebot import get_bot

bot=get_bot()
@bot.on_message('group')
async def group(ctx):
    city=ctx['message'][0]['data']['text']
    groupId=ctx['group_id']
    if groupId==894702511:
        await bot.send_group_msg(group_id=894702511,message=city)
    pass

这是我的代码

**Comment by Campanulata** [comment]
```python
from nonebot import on_command, CommandSession
from nonebot import on_natural_language, NLPSession, IntentCommand
from nonebot import get_bot

bot=get_bot()
@bot.on_message('group')
async def group(ctx):
    city=ctx['message'][0]['data']['text']
    groupId=ctx['group_id']
    if groupId==894702511:
        await bot.send_group_msg(group_id=894702511,message=city)
    pass
```

**Comment by ExerciseBook** [comment]
@Campanulata 日志中存在但是实际上没收到是腾讯风控问题。我遇到腾讯风控的其中一个缓解方案就是把机器人所有输出模板替换成英文版的（
