### ISSUE TITLE
只要开启酷q后  运行py 报错WinError 10014

### ISSUE THREAD

**Issue by gbafsh** [richardchien/nonebot#122]
之前用是好的，今天用就报错 

future: <Task finished name='Task-4' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at C:\Users\gbaf\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py:559> exception=OSError(10014, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "C:\Users\gbaf\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 562, in accept_coro
    await future
  File "C:\Users\gbaf\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 801, in loop
    conn, addr = f.result()
  File "C:\Users\gbaf\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\gbaf\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 557, in finish_accept
    return conn, conn.getpeername()
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

**Comment by richardchien** [comment]
你的 Python 版本是？

**Comment by gbafsh** [comment]
3.8.1   之前第一次可以 然后什么都没改隔了半个月 再启动 就不行了

**Comment by richardchien** [comment]
我比较怀疑还是你那边系统的问题，检查看看防火墙、磁盘空间、用户权限、Python安装之类的有没有问题，这个报错是 asyncio 报的，NoneBot
不会直接接触到

sh <notifications@github.com> 于 2019年12月31日周二 08:53写道：

**Comment by gbafsh** [comment]
就是单独运行python 和 酷q都可以 他俩一起 就报错 比如开启python 监听8080 在开启酷q 就报错 反过来也一样

**Comment by richardchien** [comment]
@gbafsh 是不是 cqhttp 的配置里面 port 和 nonebot 冲突了

**Comment by gbafsh** [comment]
教程里说的不是要一样吗 port的参数 和 json里的  都是8080 我都改成8083也不行

**Comment by richardchien** [comment]
@gbafsh 不不不，如果你的 nonebot 监听 8080，那么 cqhttp 的 port 就不应该是 8080，而应该 post_url 或者 ws_reverse_url 所配置的 nonebot 地址用 8080

**Comment by richardchien** [comment]
@gbafsh cqhttp 的 port 是 cqhttp 监听的端口，跟 nonebot 不可以一样的，建议再仔细看看文档

**Comment by gbafsh** [comment]
你是说的 5700 和 6700吗  
  "host": "[::]",
    "port": 5700,
    "use_http": true,
    "ws_host": "[::]",
    "ws_port": 6700,
    "use_ws": false,
    "ws_reverse_url": "",
    "ws_reverse_api_url": "ws://127.0.0.1:8080/ws/api/",
    "ws_reverse_event_url": "ws://127.0.0.1:8080/ws/event/",
    "use_ws_reverse": true,
    "ws_reverse_reconnect_interval": 3000,
    "ws_reverse_reconnect_on_code_1000": true,
    "post_url": "",
    "access_token": "",
    "secret": "",
    "post_message_format": "string",
    "serve_data_files": false,
    "update_source": "china",
    "update_channel": "stable",
    "auto_check_update": false,
    "auto_perform_update": false,
    "show_log_console": true,
    "log_level": "info"

**Comment by richardchien** [comment]
@gbafsh 看起来也确实没有问题

**Comment by gbafsh** [comment]
import nonebot

if __name__ == '__main__':
    nonebot.init()
    nonebot.load_builtin_plugins()
    nonebot.run(host='127.0.0.1', port=8080)
是啊 因为之前可以过  我什么都没动 在运行就不行了。
我看看不行 我换个python版本试一下 ， 酷q用的免费的酷q air

**Comment by richardchien** [comment]
找到了一个类似 issue：https://github.com/GNS3/gns3-gui/issues/2721

看起来比较奇怪，可能是 Python 3.8 引入的 bug，也可能是因为 Quart web 框架和 3.8 不兼容，暂时可能没啥好的方法，只能换环境试试

过几天我来整理一下 nonebot 这边的问题，到时候更新一下依赖版本看看能不能解决

**Comment by momocow** [comment]
@richardchien 同時看看這個 sof (https://stackoverflow.com/questions/49918525/winsock-error-10014-when-trying-to-use-a-socket-in-python-3-on-windows)

一樣是 getpeername 時報這個錯，看起來跟 python3 默認 ipv4 socket 有關係。

**Comment by gbafsh** [comment]
应该是不兼容 3.8.0,3.8.1 报错 换了 3.7.6就可以了。是最开始用的3.8.0也可以  就很奇怪 。目前3.7.6没报过错

**Comment by richardchien** [comment]
尝试升级 aiocqhttp 到 0.7.0 或更新看看，如果还不行，看看 Quart 框架是不是还是 0.6，如果是，就升级 quart 到 0.10

#130
