### ISSUE TITLE
如何获得发消息人的QQ等级 /  IP地址

### ISSUE THREAD

**Issue by nainiu233** [richardchien/nonebot#125]
为了防止QQ小号 需要获取QQ等级 或者 IP地址

**Comment by ExerciseBook** [comment]
获取QQ等级 : QQ等级pk界面，可以顺带获取vip信息。
IP地址 : [CQ:share] 存在一个让对方强制访问指定 http(s) 地址的特性。

**Comment by nainiu233** [comment]
机器人如何获取QQ等级

**Comment by richardchien** [comment]
QQ 等级可以尝试用 [这个](https://cqhttp.cc/docs/4.13/#/API?id=_get_vip_info-%E8%8E%B7%E5%8F%96%E4%BC%9A%E5%91%98%E4%BF%A1%E6%81%AF) 接口获取，但不保证可用

IP 地址目前没有接口获取
