### ISSUE TITLE
[WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

### ISSUE THREAD

**Issue by TOKAMAK9000** [richardchien/nonebot#132]
按照文档运行基础实例，却一直显示这个错误。

**Comment by TOKAMAK9000** [comment]
补充：
python版本3.7
json：
{
    "host": "[::]",
    "port": 5700,
    "use_http": true,
    "ws_host": "[::]",
    "ws_port": 6700,
    "use_ws": false,
    "ws_reverse_url": "",
    "ws_reverse_api_url": "",
    "ws_reverse_event_url": "",
    "ws_reverse_reconnect_interval": 3000,
    "ws_reverse_reconnect_on_code_1000": true,
    "use_ws_reverse": false,
    "post_url": "",
    "access_token": "",
    "secret": "",
    "post_message_format": "string",
    "serve_data_files": false,
    "update_source": "china",
    "update_channel": "stable",
    "auto_check_update": false,
    "auto_perform_update": false,
    "show_log_console": true,
    "log_level": "info"
}

**Comment by richardchien** [comment]
NoneBot 那边代码呢

**Comment by TOKAMAK9000** [comment]
使用官方文档的最小实例：

```
import nonebot

if __name__ == '__main__':
    nonebot.init()
    nonebot.load_builtin_plugins()
    nonebot.run(host='127.0.0.1', port=8080)
```

**Comment by richardchien** [comment]
@TOKAMAK9000 检查一下端口有没有被占用？比如后台可能已经开了一个没关掉

**Comment by TOKAMAK9000** [comment]
问题已解决，的确是端口占用的问题。感谢您的及时回复！
