### ISSUE TITLE
__init__() got an unexpected keyword argument 'host'

### ISSUE THREAD

**Issue by chenjambo** [richardchien/nonebot#136]
按照文档，运行[最小实例]时报错，步骤完全按照文档，python3.7.4

**Comment by richardchien** [comment]
@chenjambo 升级 aiocqhttp 到 v1.0.1 试试，刚刚推的版本，修了这个问题

**Comment by Hotobun** [comment]
我也碰到这个问题 这里的字典 直接改成关键字参数也是会报错
直接修改了 nonebot/default_config.py 默认值 
删除这里的 **字典
nonebot/__init__.py  line 25-26
super().__init__( ...   **{dict} )
