### ISSUE TITLE
/docs/guide/README.md中的超链接指向错误

### ISSUE THREAD

**Issue by Headog** [richardchien/nonebot#140]
在
https://github.com/richardchien/nonebot/tree/master/docs/guide/README.md
中
第二行“安装”的超链接应该指向https://github.com/richardchien/nonebot/blob/master/docs/guide/installation.md
而不是
https://github.com/richardchien/nonebot/blob/master/guide/installation.md

**Comment by richardchien** [comment]
这其实是 VuePress 的链接，它会正确渲染的，不过还是感谢提醒，已经全部换成了相对链接，现在在 markdown 里直接看应该也没问题了
