### ISSUE TITLE
为什么用API中的session.send()回复的字符串太长时（800个字符）会无法发送呢？

### ISSUE THREAD

**Issue by FrostMonarch95** [richardchien/nonebot#141]

**Comment by AdorableParker** [comment]
因为QQ消息有最大字数限制啊![image](https://user-images.githubusercontent.com/35246761/73606733-7c65d880-45e8-11ea-930f-5f1ab98a8288.png)

**Comment by ExerciseBook** [comment]
@AdorableParker QQ还没限制到 800 这么丧心病狂。我感觉楼主应该是被腾讯风控了。

**Comment by FrostMonarch95** [comment]
> @AdorableParker QQ还没限制到 800 这么丧心病狂。我感觉楼主应该是被腾讯风控了。

艹 被发现了吗

**Comment by FrostMonarch95** [comment]
> @AdorableParker QQ还没限制到 800 这么丧心病狂。我感觉楼主应该是被腾讯风控了。

https://github.com/NeverBehave/xixi-haha

**Comment by richardchien** [comment]
看看酷Q日志吧

**Comment by FrostMonarch95** [comment]
> 看看酷Q日志吧

日志上面有显示我发的信息 且没有error等信息 但是QQ就是没有 估计真是被tx屏蔽掉了 感谢
