### ISSUE TITLE
一个奇怪的问题

### ISSUE THREAD

**Issue by vintingb** [richardchien/nonebot#142]
同样的代码
用pycharm可以运行而直接cmd却不能运行

![2](https://user-images.githubusercontent.com/54710337/74104554-d9393400-4b90-11ea-9958-27fd23be13bf.png)

**Comment by vintingb** [comment]
![1](https://user-images.githubusercontent.com/54710337/74104575-08e83c00-4b91-11ea-96ca-6e021f6c1276.png)

**Comment by richardchien** [comment]
@vintingb 谢谢提醒，是个今天刚出现的问题，已经知道原因了，明天修

**Comment by richardchien** [comment]
@vintingb 暂时可以把 Quart 依赖包降级到 0.10.0 解决

**Comment by vintingb** [comment]
> @vintingb 暂时可以把 Quart 依赖包降级到 0.10.0 解决

改了就行了
