### ISSUE TITLE
能否提供更详细的服务器部署指南?

### ISSUE THREAD

**Issue by haowen-li** [richardchien/nonebot#146]
第一次在linux服务器上部署, 有点焦头烂额
大概摸索了一下, 步骤似乎是:
安装python3, 安装Docker Compose, (安装酷Q with HTTP API 插件?), 将机器人文件夹上传至HOME, 在HOME新建docker-compose.yml, 在机器人文件夹下新建Dockerfile, 执行docker-compose up
中间遇到很多问题不过都解决了很多... 现在卡在docker-compose up报的错上了

docker-compose up
Recreating root_nonebot_1 ... done
Recreating root_cqhttp_1  ... done
Attaching to root_nonebot_1, root_cqhttp_1
cqhttp_1   | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
nonebot_1  | python3: can't open file '/root/DicePP/dicepp.py': [Errno 2] No such file or directory
root_nonebot_1 exited with code 2
...
后面的看起来挺正常, 就是酷Q的一些信息

我直接执行 python /root/DicePP/dicepp.py是可以的, 查了下也不知道怎么解决这个问题
还有就是, 因为import ssl的问题, 重新安装了一次python, 不知道为什么python3还是不能正常导入ssl, 只有python可以... 但是我把yml文件里的python3改成python以后就提示无法识别 "python" 这个指令了. 不是很懂Docker的原理.

不知道在windows sever上会不会方便点呢?

感谢!

**Comment by richardchien** [comment]
> 直接执行 python /root/DicePP/dicepp.py是可以的

需要把 py 文件，挂载到容器里，建议先学一下 docker。Windows Server 肯定是方便点，两个东西直接打开就好。

**Comment by haowen-li** [comment]
谢谢! 这几天学了下docker, 大概明白了...

但是Nonebot的文档上找不到之前的服务器部署内容了, 是删掉了吗?

**Comment by richardchien** [comment]
> Nonebot的文档上找不到之前的服务器部署内容了

在这里 https://nonebot.cqp.moe/advanced/deployment.html

**Comment by haowen-li** [comment]
谢谢, 我现在弄的差不多了
coolq_1   | Creating default startup script /home/user/.vnc/xstartup
coolq_1   | Creating default config /home/user/.vnc/config
coolq_1   | Starting applications specified in /home/user/.vnc/xstartup
coolq_1   | Log file is /home/user/.vnc/cecb6882a2e1:11.log
coolq_1   |
coolq_1   | [CQDaemon] Starting CoolQ ....
coolq_1   | [CQDaemon] Started CoolQ .
看到这几行之前都没报错, 应该就可以了吧
但是怎么登录呢? 用noVNC吗? 好像没办法连上去, 之前似乎也没有设置过noVNC的端口之类的?

顺便一问, 安装numpy的时间特别久, 这个是正常现象么...

**Comment by richardchien** [comment]
> 用noVNC吗? 好像没办法连上去, 之前似乎也没有设置过noVNC的端口之类的?

1. 如果是 noVNC 的页面直接就打不开，那检查看看有没有把 9000 端口映射出来，还有就是服务器的安全组有没有开放端口
2. 如果是能打开 noVNC 页面，但是点连接时报错，那就尝试重新创建酷Q容器

> 安装numpy的时间特别久

可以试试换国内 PyPI 镜像源

**Comment by haowen-li** [comment]
谢谢提醒!
我在yml配置中加了个
ports:
  - "9000:9000"
然后再把服务器的端口开放就可以了连上noVNC了

设置了一番能使用了, 但是又发现了一个问题, 有些语句好像无法输出
我的代码把字符串交给与nonebot无关的代码, 处理完了以后返回一个结果字符串, 大概就是这样:
result = session.get('result')
print(f'Output:{result}')
await session.send(result)
然后发现有的命令明明已经执行完print(f'Output:{result}')了, 我可以在命令行看到输出, 但是在qq上就是收不到回复, 总是有一些固定的字符串发不出去.

当我在自己的电脑上运行的时候是没这个问题的, 所有的命令都可以收到正常的回复, 不知道是什么原因呢?

下面是一些例子:
在服务器上无法发送, PC上可以发送:
1: '火球术Fireball \n3环 塑能\n施法时间：1动作\n施法距离：150尺\n法术成分：V、S、M（一小球蝙蝠粪及硫磺）\n持续时间：立即\n 明亮的闪光从你的指间飞驰向施法距离内你指定的一点，并随着一声低吼迸成一片烈焰。目标点周围半径20尺球状区域内的每个生物必须进行以此敏捷豁免。豁免失败者将受到8d6点火焰伤害，豁免成功则伤害减半。\n 迸发的火焰将绕过拐角扩散。并点燃区域内所有未被着装或携带的可燃物件。\n 升环施法效应。使用4环或更高法术位施展该法术时，你使用的法术位每比3环高一环，其伤害就增加1d6。'

2. '骑枪 Lance\n军用近战武器 10 gp  1d12 穿刺  6 磅  触及，特殊\n使用一把长枪攻击 5 尺范围内目标时具有劣势。另外，当你不在骑乘状态时一根长枪需要两只手使用。'

服务器和PC都可以:
1. '火球项链Necklace of Fireballs\n奇物，珍稀\n这条项链上挂着1d6+3颗珠子。你可以用一个动作取下一颗珠子并投掷到至多60尺远的地方。它将在移动轨迹的终点爆炸，效果等同于3环的火球术 fireball（豁免DC 15）。\n你可以一次投掷多个珠子甚至整条项链。同时投掷的珠子数量每增加1，火球术的环阶也增加1。'
2. "找到多个匹配的条目: ['火球项链', '火球魔杖', '延迟爆裂火球', '火球术']"

ps: 我用的是亚马逊云, 下载很快, 就是Building wheel for numpy 这一步巨久...差不多要10分钟, 其他的步骤加起来可能也就30s不到

**Comment by ExerciseBook** [comment]
```
然后发现有的命令明明已经执行完print(f'Output:{result}')了, 我可以在命令行看到输出, 但是在qq上就是收不到回复, 总是有一些固定的字符串发不出去.
当我在自己的电脑上运行的时候是没这个问题的, 所有的命令都可以收到正常的回复, 不知道是什么原因呢?
```
具体见酷Q日志（不是 CQHTTP 控制台日志），如果酷Q日志显示已发送，实际上没收到的话，那是被腾讯风控了。见 https://docs.cqp.im/manual/faq/ 。
根据你的说法，我推断是异地登录保护。可以考虑到QQ安全中心手机客户端看一下。


```
我用的是亚马逊云, 下载很快, 就是Building wheel for numpy 这一步巨久...差不多要10分钟, 其他的步骤加起来可能也就30s不到
```
编译是这样的了，等一下吧。

**Comment by haowen-li** [comment]
酷Q日志显示发送了...
原来风控还是选择性屏蔽的...我以为能发出其他语句就说明没问题...
谢谢了!
