### ISSUE TITLE
发送图片私聊有反应,群聊没有反应

### ISSUE THREAD

**Issue by result-bit** [richardchien/nonebot#147]
发送图片私聊有反应,群聊没有反应

#### 代码

```python
from aiocqhttp import MessageSegment
from nonebot import on_command, CommandSession

@on_command('mzt', only_to_me=False)
async def _(session: CommandSession):
    seg=MessageSegment.image("https://www.baidu.com/img/bd_logo1.png")
    await session.send(seg)
```

用上面的代码私聊机器人可以正常发生图片,但是在群聊机器人就没有反应了.下面是一些截图...

#### 私聊截图

[![3na4OK.png](https://s2.ax1x.com/2020/02/21/3na4OK.png)](https://imgchr.com/i/3na4OK)

#### 群聊截图

[![3naIeO.png](https://s2.ax1x.com/2020/02/21/3naIeO.png)](https://imgchr.com/i/3naIeO)

#### 日志截图

[![3naowD.png](https://s2.ax1x.com/2020/02/21/3naowD.png)](https://imgchr.com/i/3naowD)

**Comment by richardchien** [comment]
酷Q有日志说明是因为腾讯风控，这个nonebot也没办法
