### ISSUE TITLE
如何取消群里面输入命令前需要的@

### ISSUE THREAD

**Issue by xiaozhe19** [richardchien/nonebot#149]
怎么取消输入前所需要的@呢
想要实现在群内直接输入命令即可回复的效果
请问怎么实现呢

**Comment by richardchien** [comment]
`@on_command(..., only_to_me=False)`

**Comment by xiaozhe19** [comment]
> `@on_command(..., only_to_me=False)`

谢谢

**Comment by turtlekey** [comment]
为什么还是不行呢？麻烦大佬帮忙看看。
![P9$RN1I G@`)JSR2(O)HPA](https://user-images.githubusercontent.com/41816645/76701533-1008e980-66fd-11ea-80f2-cd60c4ff5b21.png)

**Comment by turtlekey** [comment]
解决了，原来是下面的@on_natural_language没加这个参数。
