### ISSUE TITLE
当一个异步消息循环发送时，怎么处理其他的消息

### ISSUE THREAD

**Issue by honochika** [richardchien/nonebot#152]
我在这里做了一个循环的消息推送功能
![Uploading TIM截图20200228140147.png…]()
但是这样好像就不能并行处理其他消息了，使用kill_current_session也不行
![Screenshot_20200228_135643_com tencent tim](https://user-images.githubusercontent.com/44559164/75514695-0b70df80-5a33-11ea-8f75-51a2b901df45.png)
我想让人工能开始和停止消息的推送，请问该怎么处理

**Comment by honochika** [comment]
第一个截图的代码：
    while True:
        await push_msg(push_arr, session)
        time.sleep(60)
# push_msg是一个session.send的函数

**Comment by yanyongyu** [comment]
> 第一个截图的代码：
> while True:
> ——await push_msg(push_arr, session)
> ——time.sleep(60)
> push_msg是一个session.send的函数

用await asyncio.sleep代替time.sleep

**Comment by momocow** [comment]
time.sleep(60) 會阻塞線程，在 asyncio 裡用 await asyncio.sleep(60) 能讓其他協程繼續運行。

**Comment by yanyongyu** [comment]
@honochika 并行命令处理可以使用特权指令@on_command(xxx, privileged=True)

**Comment by honochika** [comment]
> @honochika 并行命令处理可以使用特权指令@on_command(xxx, privileged=True)
谢谢，用这个指令后收到了“推送已停止的消息”，解决了并行的问题。但是使用session.finish和kill_current_session等命令仍然不能停止之前的推送，好像是因为再次发送消息创建了新的对话的问题？有什么办法能终止原来的对话吗

`    if stripped_arg == "开始":
        while True:
            await push_msg(push_arr, session)
            await asyncio.sleep(10)
    if stripped_arg == "停止":
        session.finish('推送已停止')`

**Comment by richardchien** [comment]
> 一个循环的消息推送功能

你应该开一个新的后台异步 task 去轮询，然后在需要的时候调用发送消息等，而不是在命令处理函数里无限循环
