### ISSUE TITLE
提供Dataclass形式的ctx

### ISSUE THREAD

**Issue by mnixry** [richardchien/nonebot#153]

**Comment by momocow** [comment]
出於個人好奇，對於dataclass的應用案例也不夠熟悉，想請問一下ctx作為dataclass的需求和好處是什麼？

**Comment by mnixry** [comment]
> 出於個人好奇，對於dataclass的應用案例也不夠熟悉，想請問一下ctx作為dataclass的需求和好處是什麼？

有代码提示（逃）
感觉这样会更面向对象化一点？
从dataclass取值个人认为会比从dict取值方便一些

**Comment by momocow** [comment]
@mnixry 原來如此。

但也就表示萬一 cqhttp 修改格式，nonebot 也要隨之升版。
不過依照目前看來 ctx 內文格式還挺穩定的，應該不是太大問題。

**Comment by richardchien** [comment]
其实如果你安装的是最新版的，aiocqhttp 也是最新版的话，`session.ctx` 实际上就是 aiocqhttp 的 `event`，而这个现在部分字段已经提供只读 property 了

**Comment by richardchien** [comment]
v1.5.0 可通过 `session.event` 访问 aiocqhttp 事件对象了，这个对象是提供属性来获取内容的，比如：

```py
session.event.message
session.event.user_id
# ...
```
