### ISSUE TITLE
The docstring is not directly available for the function wrapped by `on_command` decorator.

### ISSUE THREAD

**Issue by Nuullll** [richardchien/nonebot#155]
It would be natural and convenient if one could describe the command usage in the docstring of the command handler function. 

**Desired feature:**
```python
@on_command("show_help")
async def handler(session: CommandSession):
    """Usage example"""
    session.send(f"{handler.__doc__}")   # handler.__doc__ is None
```

However, the `@on_command` decorator returns a `<class CommandFunc>` object which keeps the original function as an attribute `func`.  The docstring is not directly available.

**Workaround:**
```python
@on_command("show_help")
async def handler(session: CommandSession):
    """Usage example"""
    session.send(f"{handler.func.__doc__}")   # Usage example
```

Maybe it's better and more intuitive to offer an explicit property interface such as `CommandFunc().help`, serving as an alias of `CommandFunc().func.__doc__`
**After:**
```python
@on_command("show_help")
async def handler(session: CommandSession):
    """Usage example"""
    session.send(f"{handler.help}")   # Usage example
```

Thanks for your dedication to this remarkable project!

**Comment by richardchien** [comment]
Thanks for your issue and PR. I prefer to fix this by just removing the `CommandFunc` class, since the only purpose of introducing that class into the code was to enable auto-completion, but it never worked. A commit have been commited, and new version will be released as soon as possible (maybe tomorrow).
