### ISSUE TITLE
建议:部署篇不要一次性写入到一个docker-compose文件里

### ISSUE THREAD

**Issue by daofeng2015** [richardchien/nonebot#159]
一般第一次配置好酷q的容器后就很少重启了,倒是nonebot经常重启调试,建议分成二个项目,加入一个网络就行了

**Comment by jlkl** [comment]
docker-compose部署好之后，用docker去操纵重启nonebot的容器，酷q的容器可以还在

**Comment by richardchien** [comment]
docker-compose 可以单独重启其中一个服务的，建议搜索一下
