### ISSUE TITLE
接受消息频繁时出现堵塞的问题

### ISSUE THREAD

**Issue by haowen-li** [richardchien/nonebot#163]
当接收到消息接近每分钟120条时(其中要处理的命令高峰时大约每秒一两条), 发送回复的延迟非常明显, 有时会卡住二三十秒以后才会一起发送, 而有些消息(非指令)的状态会一直保持"处理中"十几秒. 有时候也会出现未收到服务器回馈和事件队列已满的报告, 但有的时候也不会报任何的错, 只是反馈的消息在半分钟左右才会一起回复. 严重的时候酷q和nonebot的日志都会卡住, 等半分钟至几分钟的时间才会恢复正常并回复全部消息. 

我使用了两个on_natural_language处理指令, 只有消息的开头第一个字符是'.'或'。'才会进一步处理消息, 否则就直接无视, 其中一个是only_at_me才会执行, 和另一个一模一样. 进一步处理消息不涉及IO操作, 最复杂的指令也就是对不到4000个左右的短字符串挨个执行.find, 平时回复得都很快, 回复的语句一般在十几个字符到100个字符之间. 服务器是台湾的谷歌云, cpu,内存和硬盘占用都非常低, 带宽10mb/s左右, ping qq.com的延迟接近200ms. 不知道是不是网络的问题, 但是有的时候延迟接近半分钟甚至发送失败就无法理解了...

**Comment by haowen-li** [comment]
使用酷qpro自带的状态监测显示cpu占用率100%, 但是docker stats显示cpu占用率都在5%以下...

**Comment by richardchien** [comment]
> 最复杂的指令也就是对不到4000个左右的短字符串挨个执行.find

这个操作听起来对某些特殊输入可能导致 CPU 疯狂运算

还有就是要确保 NoneBot、aiocqhttp、CQHTTP 插件都是最新版，其中 CQHTTP 插件在 4.14.0 之前存在连续发图（或其他耗时的消息）时可能阻塞的问题

**Comment by haowen-li** [comment]
谢谢, 问题出在CPU上, 谷歌云的共享核心太菜了, 偏偏还告诉我占用率很低... 换到自己电脑上跑就好了 T T
