### ISSUE TITLE
CommandSession的get方法增加validator参数

### ISSUE THREAD

**Issue by waylonwang** [richardchien/nonebot#18]
目前CommandSession的args解析通过args_parser进行，所有的参数在一个方法中进行解析和校验，当参数比较多时代码显得非常的臃肿，各种if堆砌，不同参数的解析与校验过于耦合、职责不清，CommandSession的get方法中仅对参数的必录（为空）做了校验及提示，建议在CommandSession的get方法中增加validators参数，validators可为列表类型，支持多个校验器，每个validator校验器参数包含一个内置或自定义的验证方法的入口，及一个返回失败时的消息提示，None本身也可以提供一组缺省的内置校验器，例如数据必录（为空）的校验转为一个校验器，还可以增加数据类型(Number、Date等)的校验器，具体可以参见wtforms的validators.py

调用的方式可以是这样的：
arg1 = session.get('arg1', [(none.validators.required,  '要查询的arg1是什么？')] )
arg2 = session.get('arg2',[(none.validators.required,  '要查询的arg2是什么？'), (my_validator_func, '你输入了无效的arg2，请重新输入arg2')])

**Comment by richardchien** [comment]
诶，这样不错啊，不过我最近可能没空折腾这个，你前面几个 issue 也没还来得及处理，可能需要过段时间，到 11 月中旬的样子

**Comment by waylonwang** [comment]
> 诶，这样不错啊，不过我最近可能没空折腾这个，你前面几个 issue 也没还来得及处理，可能需要过段时间，到 11 月中旬的样子

OK

**Comment by richardchien** [comment]
v1.2.0 加入了这种调用方式，具体看 [更新日志](https://none.rclab.tk/changelog.html#v1-2-0)，实现跟你给出的不太一样，但思路基本一致
