### ISSUE TITLE
是否有办法实现拦截 CoolQ 的消息（不让它再将消息传递给下一个插件）

### ISSUE THREAD

**Issue by ImSingee** [richardchien/nonebot#32]
看 Http API 是可以实现同步拦截的，不过查了 aiocqhttp 和 none 的文档没找到同步并且拦截消息的办法

**Comment by richardchien** [comment]
aiocqhttp 是可以的，不过只限 HTTP 方式通信

**Comment by ImSingee** [comment]
反向 websocket 方式不可以吗…

所以未来可能可以吗…

**Comment by richardchien** [comment]
WebSocket 目前都是插件直接发了就不管，目前应该没有计划加这个，这个需要插件等待后端响应，改动有点大

Singee <notifications@github.com>于2018年12月27日 周四09:39写道：
