### ISSUE TITLE
触发Lifespan error

### ISSUE THREAD

**Issue by amongtheflowers** [richardchien/nonebot#34]
操作系统:windows
py版本：3.6.6
cqhttpapi版本：4.7.0
none 版本 ：0.4.2~0.52(都有)
提示内容:[2018-12-26 19:51:06,002] ASGI Framework Lifespan error, continuing without Lifespan support
引发第三方库：quart,hypercorn

**Comment by richardchien** [comment]
> 这是 Quart 的问题，换 3.7 环境可解

我昨天跟他讨论了，这个问题，是 Quart 0.6.x 和 Hypercorn 0.4.x 一起用出现的问题，主要问题在于 Hypercorn。实际上因为 aiocqhttp 现在依赖 Quart~=0.6，导致即使是 Python 3.7 也会安装上述两个版本的组合，仍然会有问题。

可以考虑 aiocqhttp 的依赖仍然改成 >=0.6，这样 Python 3.7 会安装 0.7.x，而 Python 3.6 会安装 0.6.x，也就只有一部分人会遇到这个问题了

**Comment by ImSingee** [comment]
aiocqhttp 的依赖仍然改成 >=0.6 的话我遇到的问题是 Python3.6 会直接安装 0.7 然后报需要 Python>3.7 然后安装不了

**Comment by richardchien** [comment]
我刚刚测试了一下，即使是 Python 3.7 安装了 Quart 0.7.x，最新版，WebSocket 访问日志也已经修改了，我问了 Hypercorn 作者，他说：

> It still access logs, however the Websocket access log has changed such that it logs only after the connection has closed (is complete). This means the timing part represents the duration of the connection. I'm open to suggestions on Websocket access logs...

现在的行为全部是 ws 连接断开后才会有日志，这就比较尴尬

**Comment by richardchien** [comment]
目前 Hypercorn 作者 [已经修改了 WebSocket 日志行为](https://gitlab.com/pgjones/hypercorn/issues/43#note_131697973)，应该会在下个版本发布

**Comment by richardchien** [comment]
OK，最终确定一下：

> ASGI Framework Lifespan error, continuing without Lifespan support

这个错误不存在问题，可以忽略，而且事实上只是一个 warning。

当时的问题主要在于 WebSocket 连接后没有日志（实际上会在断开后才打日志），我去给作者提了 issue 之后，他已经把日志移到建立连接时了，**目前升级 Hypercorn 到 0.5 版本就一切正常了**。Lifespan error 仍然存在，等最初的问题已经解决了。
