### ISSUE TITLE
打算更改 package 的名字，大家有什么意见吗

### ISSUE THREAD

**Issue by richardchien** [richardchien/nonebot#35]
现在 PyPI 上的包名叫 `none-bot`，实际导入的包名叫 `none`，并且 PyPI 上已经存在一个叫 `none` 的包。打算改名为 `nonebot`，统一安装和导入的包名（这个改动可能需要修改现有应用代码），大家觉得有没有什么问题？或者其他建议？

**Comment by richardchien** [comment]
> 建议在 pypi 上新传一个包吧

诶，这个方案不错

> 另外 nonebot 可能会报拼写检查错误

PyCharm 默认不会对 package name 做拼写检查

**Comment by ImSingee** [comment]
@theprimone 对于这种。。普遍做法应该是现在的包最后一个版本一运行就给一个 warning 告诉换包了

**Comment by theprimone** [comment]
@ImSingee 秀啊 没发过包的我不是很懂这个 不过一说好像见过这种操作 deprecated提示？

**Comment by richardchien** [comment]
新的包已经发布了
