### ISSUE TITLE
酷Q  pro 版遇到的bug

### ISSUE THREAD

**Issue by mabi-zafeishiya** [richardchien/nonebot#37]
```
Task exception was never retrieved
future: <Task finished coro=<ASGIWebsocketConnection.handle_websocket() done, defined at C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\asgi.py:128> exception=AttributeError("'NoneType' object has no attribute 'pop'") created at C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\asgi.py:102>
source_traceback: Object created at (most recent call last):
  File "D:\coolq\py\bot.py", line 10, in <module>
    none.run()
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\none\__init__.py", line 104, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\none\__init__.py", line 58, in run
    *args, **kwargs)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiocqhttp\__init__.py", line 224, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\app.py", line 1359, in run
    run_single(self, config, loop=loop)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hypercorn\asyncio\run.py", line 159, in run_single
    loop.run_until_complete(gathered_tasks)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1767, in _run_once
    handle._run()
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hypercorn\asgi\wsproto.py", line 127, in handle_websocket
    await self.handle_asgi_app(event)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hypercorn\asgi\wsproto.py", line 139, in handle_asgi_app
    await asgi_instance(self.asgi_receive, partial(self.asgi_send, event))
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\asgi.py", line 102, in __call__
    handler_task = asyncio.ensure_future(self.handle_websocket(websocket, send))
Traceback (most recent call last):
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\asgi.py", line 129, in handle_websocket
    response = await self.app.handle_websocket(websocket)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\app.py", line 1589, in handle_websocket
    return await self.handle_websocket_exception(error)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\ctx.py", line 133, in __aexit__
    await super().__aexit__(exc_type, exc_value, tb)
  File "C:\Users\sijj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\ctx.py", line 61, in __aexit__
    await _app_ctx_stack.top.pop(exc_value)
AttributeError: 'NoneType' object has no attribute 'pop'
[2018-12-27 11:05:29,570] 127.0.0.1:56030 GET /ws/event/ ws 101 - 48895135
```

**Comment by mabi-zafeishiya** [comment]
首先 酷Q air版本没这个问题。升级为pro时候遇到的。
我先启动的自己写的机器人脚本，再启动酷Q，我在脚本的代码里面做了一次http请求，请求结束做了一次数据解析。就报上面的错了。
但是如果我先启动的酷Q，再启动自己写的脚本，就不会出现这个错误

**Comment by mabi-zafeishiya** [comment]
这个错误发生之后，脚本就再也收不到数据了，两者之间的交互就断了。目前就是靠上面说的启动顺序来规避这个错误发生QAQ

**Comment by richardchien** [comment]
每次都能复现？

**Comment by mabi-zafeishiya** [comment]
差不多，频率很高。需要的话 我也给你我的代码。不过感觉应该不是代码的问题。

**Comment by mabi-zafeishiya** [comment]
from none import on_command, CommandSession
import json
from bs4 import BeautifulSoup
import none
# from luoqi.plugins import shifang
from luoqi.plugins import my_http
import re

config = []
headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6',"contentType":"text/html; charset=utf-8"}

############################## help ###############################
# on_command 装饰器将函数声明为一个命令处理器
@on_command('shifang', aliases=( '释放卷', '释放','shifan','shifang'), only_to_me=False)
async def chashifang(session: CommandSession):
    global config
    # 从 Session 对象中获取城市名称（city），如果当前不存在，则询问用户
    if session.get('param', prompt='查询失败？') == False:
        return
    juan = session.get('juan', prompt='查询失败？')
    if config == [] or juan == "更新" or juan == "update":
        await session.send("释放卷内容更新中，请稍后查询")
        result = await update_shifang_config()
        if not result:
            await session.send("释放卷内容更新失败，请重新更新")
            return
        if juan == "更新" or juan == "update":
            await session.send("释放卷内容更新成功")
            return
    userid = None
    if "group_id" in session.ctx:
        userid = session.ctx['user_id']
    juan_info = await get_info_of_juan(juan,userid)
    # print(session.ctx)
    await session.send(juan_info)

# weather.args_parser 装饰器将函数声明为 weather 命令的参数解析器
# 命令解析器用于将用户输入的参数解析成命令真正需要的数据
@chashifang.args_parser
async def _(session: CommandSession):
    session.args['param'] = True
    # 去掉消息首尾的空白符
    stripped_arg = session.current_arg_text.strip()
    if not stripped_arg:
        session.args['param'] = False
    if session.current_key:
        # 如果当前正在向用户询问更多信息（本例中只有可能是要查询的城市），则直接赋值
        session.args[session.current_key] = stripped_arg
    elif stripped_arg:
        # 如果当前没有在询问，但用户已经发送了内容，则理解为要查询的城市
        # 这种情况通常是用户直接将城市名跟在命令名后面，作为参数传入
        session.args['juan'] = stripped_arg

async def update_shifang_config() -> str:
    global config
    print("aaaaaaaaaaa")
    result = my_http.api_query("https://github.com/zafeishiya/mabinogy/blob/master/shifang.txt", headers)
    if not result:
        return ""
    print("000000000000")
    soup = BeautifulSoup(result, 'lxml')
    print("11111111")
    info = soup.select('table[class="highlight tab-size js-file-line-container"]')[0].get_text().strip().replace(
        "&quot;", '"').replace("&gt", " ").replace(r"\n", "").replace("\n", "").replace("\\", "").replace("\t", "")
    print("22222222")
    info = re.sub(r", *\]", "]", info)
    print("33333333")
    #print(info)
    config = json.loads(info)
    return "123"


async def get_info_of_juan(name: str,userid:str) -> str:
    #return f'[CQ:at,qq=504615289]\n {name}的天气是……'
    # 这里简单返回一个字符串
    result = ""
    contain_list = []
    equal_list = []
    for info in config:
        if info[0] == name:
            equal_list.append(info)
        elif name in info[0] or info[0] in name:
            contain_list.append(info)
    if len(equal_list) == 0:
        result += "找不到释放卷：" + name + '\n'
    else:
        for info in equal_list:
            result += info[0]+ "\n"
            result += "" +info[1]+ "\n"
            result += "位置：" + info[2]+ "\n"
            result += "属性效果：" + info[3]+ "\n"
            result += "来源：" + info[4] + "\n"
            result += "----------------\n"
    if len(contain_list) > 0:
        result += "你可能要查找的是： "
        for info in contain_list:
            result += info[0]  + "? "
    if userid:
        result = f'[CQ:at,qq={userid}]\n' + result
    result += "\n数据来源:迪尔纳诺。"
    return result







我写了三个脚本，上面这个是报错最频繁的脚本。
第一个脚本没有做http 请求，基本不会报错。
第二个脚本请求的数据不是很大，拉取了我在github上面的提交的文件内容。报错概率比较低
第三个就是上面的脚本，拉取的数据量比较大，url在代码里面有。基本90%会报错。

先开脚本，再启动或重启酷Q才会报错

**Comment by richardchien** [comment]
emmm，你的代码，用 ``` 包裹一下吧，已经完全看不出来了

**Comment by mabi-zafeishiya** [comment]
加了。。原来还可以用三个`的么。尴尬。

**Comment by richardchien** [comment]
> result = my_http.api_query("https://github.com/zafeishiya/mabinogy/blob/master/shifang.txt", headers)

你这个 HTTP 请求的地方需要使用 aiohttp 之类的异步 IO 的库

**Comment by sijunjie** [comment]
```
async def fetch(session, url):
    async with session.get(url) as response:
        return await response.text()

async def update_shifang_config() -> str:
    global config
    print("aaaaaaaaaaa")
    #result = my_http.api_query("https://github.com/zafeishiya/mabinogy/blob/master/shifang.txt", headers)
    result = ""
    async with aiohttp.ClientSession() as session:
        result = await fetch(session, "https://github.com/zafeishiya/mabinogy/blob/master/shifang.txt")
    if not result:
        return ""
    print("000000000000")
    soup = BeautifulSoup(result, 'lxml')
    print("11111111")
    info = soup.select('table[class="highlight tab-size js-file-line-container"]')[0].get_text().strip().replace(
        "&quot;", '"').replace("&gt", " ").replace(r"\n", "").replace("\n", "").replace("\\", "").replace("\t", "")
    print("22222222")
    info = re.sub(r", *\]", "]", info)
    print("33333333")
    print(info)
    config = json.loads(info)
    return "123"
```
我把代码换成了aiohttp，还是一样的问题.

**Comment by richardchien** [comment]
@yorushika 甚至开始版聊了（

**Comment by sijunjie** [comment]
是啊，我的数据迪尔纳诺爬的，所以带上了0 0

**Comment by richardchien** [comment]
你这个新的代码我测试没有问题
![image](https://user-images.githubusercontent.com/5317095/50507314-ea6fd000-0ab7-11e9-9e28-8bfd340c18d1.png)

**Comment by richardchien** [comment]
我又试了先启动脚本，也没问题（
