### ISSUE TITLE
按照教程 启动不了bot.py

### ISSUE THREAD

**Issue by xyl2019** [richardchien/nonebot#45]
![qq 20190120115517](https://user-images.githubusercontent.com/46856158/51435085-acc32900-1caa-11e9-9ca0-30f4bef0953e.png)

**Comment by xyl2019** [comment]
![qq 20190120120244](https://user-images.githubusercontent.com/46856158/51435133-6d490c80-1cab-11e9-9ddc-687d2fdbace5.png)
请问这个是出现了什么问题呢？

**Comment by richardchien** [comment]
这个没问题，可以忽略

**Comment by xyl2019** [comment]
![default](https://user-images.githubusercontent.com/46856158/51435320-df235500-1caf-11e9-99ed-bf633dac1bbf.png)
![default](https://user-images.githubusercontent.com/46856158/51435321-dfbbeb80-1caf-11e9-8bef-3015ad280843.png)

**Comment by richardchien** [comment]
@xyl2019 https://none.rclab.tk/guide/getting-started.html#%E9%85%8D%E7%BD%AE-coolq-http-api-%E6%8F%92%E4%BB%B6

**Comment by xyl2019** [comment]
![default](https://user-images.githubusercontent.com/46856158/51435820-a6897880-1cbb-11e9-82a8-35f925db31a4.png)
这样子吗？

**Comment by richardchien** [comment]
@xyl2019 不是，要不先了解一下JSON的语法？
