### ISSUE TITLE
文档中api里的delete_msg使用后报错

### ISSUE THREAD

**Issue by JadyXuan** [richardchien/nonebot#47]
![default](https://user-images.githubusercontent.com/35390572/51466867-2429b300-1da6-11e9-9082-ce74b968e84f.JPG)

**Comment by richardchien** [comment]
@JadyXuan 必须使用命名参数，仔细看看文档的加粗部分？

**Comment by JadyXuan** [comment]
@richardchien 好的谢谢啦，没有仔细看^^
