### ISSUE TITLE
我配置错了吗，内置插件调试不成功

### ISSUE THREAD

**Issue by xiaohuimc** [richardchien/nonebot#50]
![image](https://user-images.githubusercontent.com/28799892/51798109-1366ba80-2248-11e9-930f-f3d82b453c9a.png)

![image](https://user-images.githubusercontent.com/28799892/51798115-29747b00-2248-11e9-8c35-b1b7d59a32d7.png)

**Comment by richardchien** [comment]
@xiaohuimc 怪我，怪我，文档有个地方有错误，待会儿改一下

**Comment by xiaohuimc** [comment]
好的  尴尬
