### ISSUE TITLE
关于群管功能的踢人，禁言之类的api调用

### ISSUE THREAD

**Issue by AdorableParker** [richardchien/nonebot#51]
CoolQ HTTP中的 set_group_kick之类的api，是需要如何调用呢，或是还未整合进nonebot里面，需要自行解决呢？

**Comment by richardchien** [comment]
@AdorableParker 仔细读文档哦，指南里面有 调用 CQHTTP 接口 相关内容

**Comment by richardchien** [comment]
如果没有找到的话，在 [这里](https://none.rclab.tk/guide/calling-cqhttp-api.html)

**Comment by AdorableParker** [comment]
已经解决，忘了回复，抱歉，感谢提醒
