### ISSUE TITLE
我想请问一下怎么根据别人的回复发一个图片或者一个文件？

### ISSUE THREAD

**Issue by xyl2019** [richardchien/nonebot#55]
我想请问一下怎么根据别人的回复发一个图片或者一个文件？

**Comment by richardchien** [comment]
在文档的术语表里面了解一下 CQ 码，注意顺着给出的链接深入

另外只能发送图片，不能发送文件

xyl2019 <notifications@github.com>于2019年2月23日 周六16:53写道：

**Comment by xyl2019** [comment]
请问我这样子写为什么会报错呢？  我把图片存在了酷Q目录下的data\image底下了，文件名是week8.png
![image](https://user-images.githubusercontent.com/46856158/53285664-32e8f880-379e-11e9-901d-b2222ba4747d.png)
![image](https://user-images.githubusercontent.com/46856158/53285673-4300d800-379e-11e9-9d57-c8c3c180a21b.png)
