### ISSUE TITLE
一个关于传图片的问题

### ISSUE THREAD

**Issue by xyl2019** [richardchien/nonebot#57]
我看了那个CQ码的介绍后写了一段程序调试了一下出现了错误，不知道问题出现在哪里，能否麻烦各位告诉我怎么改吗？
我把那个图片存在了酷Q的data\image下面 然后文件名是week8.png
![image](https://user-images.githubusercontent.com/46856158/53285999-f23fae00-37a2-11e9-8fca-c007115a7969.png)
![image](https://user-images.githubusercontent.com/46856158/53286003-fb307f80-37a2-11e9-91cf-b2c6fa690ddd.png)

**Comment by richardchien** [comment]
直接 `MessageSegment.image('week8.png')` 就可以了

**Comment by richardchien** [comment]
你遇到的问题是我文档笔误，再看一下，现在更新了，应该是 `type_='image'`
