### ISSUE TITLE
希望在session中添加用户信息的属性

### ISSUE THREAD

**Issue by aboutmydreams** [richardchien/nonebot#58]
希望在session中添加用户信息的属性以方便在回复时增加扩展性

**Comment by richardchien** [comment]
@aboutmydreams 实际上有，在 `session.ctx`

**Comment by aboutmydreams** [comment]
嗯嗯 不好意思 我后来读了源码才发现，看了一下另外一个关于nonebot发展的issue。真心认为 作者好棒 希望一年后有机会看见作者更完美的框架~

**Comment by aboutmydreams** [comment]
再请教一下关于url换行的问题 
http://127.0.0.1:5700/send_private_msg?user_id=1097977702&message=后面的长文本消息如何实现换行处理呢

**Comment by richardchien** [comment]
@aboutmydreams 对换行符进行 url encode
