### ISSUE TITLE
使用nonebot.command模块的permission参数时，传入文档给出的常量提示变量名不存在

### ISSUE THREAD

**Issue by AdorableParker** [richardchien/nonebot#60]
![image](https://user-images.githubusercontent.com/35246761/54066968-18ba1a80-4274-11e9-9d39-3d5ecf9147a0.png)
如图，貌似是变量作用域的问题，直接传入常量值可以正常运行

**Comment by amongtheflowers** [comment]
需要导入
```bash
from nonebot.permission import GROUP_ADMIN
```

**Comment by AdorableParker** [comment]
所有常量使用时都需要导入是吗？感谢。

**Comment by richardchien** [comment]
@AdorableParker 这属于 Python 语法问题（
