### ISSUE TITLE
和其他async异步模块的兼容问题

### ISSUE THREAD

**Issue by Evisolpxe** [richardchien/nonebot#62]
你好！requests_html同样也使用了async进行异步抓取，在和bot同时使用的时候会报This event loop is already running错误。请问在使用其他异步模块的时候该怎么写才能正确运行呢？

**Comment by richardchien** [comment]
通常解决办法是把其它 aio 库的调用改成 在 NoneBot（也就是 Hypercorn）的 loop 里面创建新的 task
