### ISSUE TITLE
关于on_command命令匹配CQ码的问题

### ISSUE THREAD

**Issue by NekodRider** [richardchien/nonebot#64]
想要实现一个能匹配所有at消息的功能(不止是at机器人)
尝试直接按照CQ码字符串的方式无法匹配 同时直接发送“[CQ:at,qq=xxxx]”也显示接收到的是转义后的字符串，请问能否有办法实现这一功能？
```Python
@on_command('[CQ:at,qq=xxxx]', only_to_me=False)
```

**Comment by richardchien** [comment]
@NekodRider 用 @bot.on_message 然后遍历消息段吧

**Comment by NekodRider** [comment]
@richardchien 成功了 感谢
