### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by Nicholasjl** [richardchien/nonebot#65]
我在on_natural_language里面加入permission参数试图让bot不对私聊进行回复，但是把权限表试了一遍除了0x0000之外都不起作用

**Comment by richardchien** [comment]
@Nicholasjl 大概因为你设置了超级用户？把自己从 SUPERUSERS 里面删掉试试

**Comment by Nicholasjl** [comment]
> @Nicholasjl 大概因为你设置了超级用户？把自己从 SUPERUSERS 里面删掉试试

确实是这个原因  谢谢大佬
