### ISSUE TITLE
能否接收新命令而不影响原有命令执行

### ISSUE THREAD

**Issue by wuhuanyan** [richardchien/nonebot#66]
### `SESSION_RUN_TIMEOUT`

- **类型:** `Optional[datetime.timedelta]`

- **默认值:** `None`

- **说明:**

  命令会话的运行超时时长，超时后会话将被移除，但不会停止此会话已经在运行的函数，它仍然会继续在后台执行。此时用户可以调用新的命令，开启新的会话。`None` 表示不超时。

- **用法:**

  ```python
  from datetime import timedelta
  SESSION_RUN_TIMEOUT = timedelta(seconds=10)
  ```

  设置运行超时为 10 秒，即命令会话运行达到 10 秒，NoneBot 将认为它已经结束。

**Comment by wuhuanyan** [comment]
我已经在nonebot的配置文件中设定了这个值
```
SESSION_RUN_TIMEOUT = timedelta(seconds=1)
```

但是在超时之后，函数好像就被停止了。
```
@on_command('jjyj', aliases=['Jjyj'], only_to_me=False)
async def jjyj(session: CommandSession):
    fromUserID = session.ctx['user_id']
    bot = get_bot()
    await bot.send_private_msg(user_id=fromUserID, message='jjyj函数已接收!请等待10秒')
    for i in range(0, 10):
        # await bot.send_private_msg(user_id=fromUserID, message=f'jjyj函数正在运行中!请等待{10 - i}秒')
        print(i)
        await asyncio.sleep(1)
    await bot.send_private_msg(user_id=fromUserID, message=f'jjyj函数运行结束!结果为:xxxxx')
```

**Comment by richardchien** [comment]
目前的逻辑就是这样，超时之后任务就被中断了，见 [实现代码](https://github.com/richardchien/nonebot/blob/master/nonebot/command/__init__.py#L627)。

如果需要超时之后仍然执行，可以将异步任务通过 `asyncio.ensure_future()` 等方式送入 loop，然后在命令处理函数中去 await 它，这样的话超时之后刚刚加入 loop 的任务应该是可以继续执行的（未经测试，可能需要自行测试一下）

**Comment by wuhuanyan** [comment]
```
但不会停止此会话已经在运行的函数，它仍然会继续在后台执行。
```
所以这里“会话已经在运行的函数”，并不是指我的代码中的jjyj函数？

我目前简单的通过在`handle_command`里面`if session.running:`创建一个新的会话。
你的建议我会研究一下，今天太晚。

**Comment by richardchien** [comment]
看来文档忘记及时更新了，这块的代码以前是直接移除 session，现在是 `asyncio.wait_for`，超时直接抛异常了，回头我改下文档

wuhuanyan <notifications@github.com>于2019年4月14日 周日22:32写道：
