### ISSUE TITLE
能不能发群公告

### ISSUE THREAD

**Issue by bolind86** [richardchien/nonebot#67]

**Comment by AdorableParker** [comment]
可以的，用Cool Q HTTP API，不过是实验性的api，可能会有问题，

**Comment by AdorableParker** [comment]
API参考链接：https://cqhttp.cc/docs/4.10/#/API?id=_send_group_notice-%E5%8F%91%E5%B8%83%E7%BE%A4%E5%85%AC%E5%91%8A

**Comment by bolind86** [comment]
> API参考链接：https://cqhttp.cc/docs/4.10/#/API?id=_send_group_notice-%E5%8F%91%E5%B8%83%E7%BE%A4%E5%85%AC%E5%91%8A

谢谢
