### ISSUE TITLE
RuntimeWarning: coroutine '_' was never awaited

### ISSUE THREAD

**Issue by Dawnnnnnn** [richardchien/nonebot#68]
https://none.rclab.tk/guide/scheduler.html#%E5%AE%9A%E6%97%B6%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF

我在尝试使用定时器的过程中运行示例代码出现了如图所示Warning，函数是用async声明的，调用发送群消息也是await的，在酷Q的日志中也无任何反馈。结果就是消息没发出去。

![image](https://user-images.githubusercontent.com/24506421/56718809-10f5fd00-6772-11e9-9925-5925a115aeeb.png)

**Comment by Dawnnnnnn** [comment]
```py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2019-04-25 13:17
# @Author  : Dawnnnnnn
# @Contact : 1050596704@qq.com
import nonebot
import requests
import traceback
import asyncio

from datetime import datetime
import nonebot
import pytz
from aiocqhttp.exceptions import Error as CQHttpError

@nonebot.scheduler.scheduled_job('interval', seconds=10)
async def _():
    bot = nonebot.get_bot()
    now = datetime.now(pytz.timezone('Asia/Shanghai'))
    try:
        await bot.send_group_msg(group_id=12345678,
                                 message=f'现在{now.hour}点整啦！')
    except CQHttpError:
        pass
```

**Comment by AdorableParker** [comment]
是否是second拼写错误呢
![image](https://user-images.githubusercontent.com/35246761/56720421-6384e880-6775-11e9-90ca-0037f45f068d.png)

**Comment by Dawnnnnnn** [comment]
interval 应该就是要加s的。。

```
除了 cron，还有两种触发器类型 interval 和 date。例如，你可以使用 nonebot.scheduler.scheduled_job('interval', minutes=10) 来每十分钟执行一次任务。
```

文档是这么写的。。

**Comment by AdorableParker** [comment]
不明，我这边执行正常
![image](https://user-images.githubusercontent.com/35246761/56721054-aabfa900-6776-11e9-811c-e9973ed96e9b.png)
![image](https://user-images.githubusercontent.com/35246761/56721066-b0b58a00-6776-11e9-99d1-5686289e6f8f.png)

**Comment by Dawnnnnnn** [comment]
好奇怪。。。我把另一个插件停了试试，顺便问下python版本是多少呢

**Comment by AdorableParker** [comment]
我这边用的Anaconda Python 3.7.0

**Comment by Dawnnnnnn** [comment]
好的，谢谢

**Comment by Dawnnnnnn** [comment]
升级了Python版本到3.7.3就好了。。我原来是3.6.4
