### ISSUE TITLE
新人加群事件捕获并批准后，能不能立刻发起一个私聊消息？

### ISSUE THREAD

**Issue by awayme** [richardchien/nonebot#70]
在@on_request('group')对应的回调函数里approve加群请求后，在@on_notice('group_increase') 对应回调里捕获到了事件，
使用await session.send('欢迎')可以正常在群里发消息，
但使用await session.send('幻音',  ensure_private=True)无法发起私聊，
也尝试了await session.send('欢迎', user_id=ctx['user_id'], ensure_private=True)，还是不行

正确在群里发起私聊的调用方式是怎样的呢？谢谢

**Comment by ExerciseBook** [comment]
@awayme 貌似需要私聊目标曾经在机器人所在的QQ群发过言或者曾经私聊过机器人或者是机器人的好友才能发送成功？

**Comment by sosyz** [comment]
@awayme 无法主动私聊。。除非好友或者机器人曾收到过这个人发的消息保存了关系
