### ISSUE TITLE
怎么问一句回一句？

### ISSUE THREAD

**Issue by cleoold** [richardchien/nonebot#71]
Want to have:
```
>命令 [param0]
请输入参数1
>dasffasfagg
请输入参数2
>dafawfawf
...
结果是：...
```
Tried
```python
param0 = session.get('param0')
param1 = session.get('param1', prompt='请输入参数1')
param2 = session.get('param2', prompt='请输入参数2')
```
Which does not work?
--------------Solved----------------------------
是`privileged=True`的问题，取消就能回复了。

**Comment by richardchien** [comment]
`privileged=True` 只适用于需要优先于其它一切命令的命令，比如杀死当前 session 之类的。

既然解决了我就 close 啦

**Comment by cleoold** [comment]
> 
> 
> `privileged=True` 只适用于需要优先于其它一切命令的命令，比如杀死当前 session 之类的。
> 
> 既然解决了我就 close 啦

不过打开了这个就不能向问题那样分步传参数了。比如教程里的天气，开了这个在我只输入`天气`之后在输入`上海`就没动静了，session在控制台里看到也没有结束。这是预设的吗？

**Comment by richardchien** [comment]
@cleoold 特权命令是不会覆盖当前 session 的，所以只会运行一次
