### ISSUE TITLE
CQHTTP收得到消息，但nonebot收不到消息

### ISSUE THREAD

**Issue by RuiLiFeng** [richardchien/nonebot#73]
按照教程里面的最小实例配置的，但是一直连不上nonebot
![image](https://user-images.githubusercontent.com/33709183/59202028-480f5900-8bce-11e9-8255-2a9d71962218.png)
![image](https://user-images.githubusercontent.com/33709183/59202038-4b0a4980-8bce-11e9-96b9-f73f66d7dcaf.png)
![image](https://user-images.githubusercontent.com/33709183/59202053-5493b180-8bce-11e9-80d5-1cae60fa7cff.png)

**Comment by RuiLiFeng** [comment]
![image](https://user-images.githubusercontent.com/33709183/59202102-65442780-8bce-11e9-8e10-754339c1a35b.png)
![image](https://user-images.githubusercontent.com/33709183/59202116-6c6b3580-8bce-11e9-8194-c7cc4750349c.png)
![image](https://user-images.githubusercontent.com/33709183/59202128-6f662600-8bce-11e9-8229-50855c9467d3.png)

**Comment by richardchien** [comment]
检查一下看看是不是有什么程序占用了 8080 端口

RuiLiFeng <notifications@github.com> 于 2019年6月10日周一 22:23写道：

**Comment by RuiLiFeng** [comment]
非常感谢！问题已解决
