### ISSUE TITLE
关键词，敏感词屏蔽

### ISSUE THREAD

**Issue by GloomyGhost-MosquitoSeal** [richardchien/nonebot#74]
如题，这个东西没有，封群危险过大（
请问能不能整合到核心，或者请您告诉我相关处理的代码，我来提交一个pr。

**Comment by richardchien** [comment]
你可以使用 `@nonebot.message_preprocessor` 装饰器来对消息进行预处理，发现有敏感词可以直接随便抛个异常来终止消息处理，或者把 `ctx['message']` 改成其它内容
