### ISSUE TITLE
可不可以一个进程加载一个插件呢？

### ISSUE THREAD

**Issue by JoffreyN** [richardchien/nonebot#77]
plugins目录下的插件

**Comment by xtaodada** [comment]
@JoffreyN 你以为你是Chrome？一个进程一个页面（不对

**Comment by richardchien** [comment]
@JoffreyN 目前不行，因为 nonebot 用的是 asyncio 导致不太好这么玩，但你可以自己在插件中启动并维护新的进程或者进程池
