### ISSUE TITLE
on_natural_language装饰器存在数据类型导致的匹配错误问题

### ISSUE THREAD

**Issue by yorushika** [richardchien/nonebot#78]
示例需求：在聊天内容包含*ABC*时触发。

`@on_natural_language(keywords=('ABC',), only_to_me=False)`

这样的代码可以正常工作。

但如果少打一个逗号变成这样

`@on_natural_language(keywords=('ABC'), only_to_me=False)`

功能会变为：在聊天内容包含**A或B或C**时触发。

**Comment by richardchien** [comment]
@yorushika 你需要学习 Python 的 tuple

**Comment by richardchien** [comment]
PR 已合并到 master 分支
