### ISSUE TITLE
如何使用nonebotAPI中的类

### ISSUE THREAD

**Issue by yuguangzsl** [richardchien/nonebot#83]
我想实现有人进群就艾特他然后让他改名片，发现nonebot.message中的MessageSegment有at这个功能，我from nonebot import message,然后seg=MessageSegment.at(user_id),然后await bot.send_group_msg(message= seg+'欢迎,进群请改名片') 报错没有命名MessageSegment。请问是导入模块有问题吗（顺便问下可以在这里问这种萌新看不懂api文档的问题吗）

**Comment by amongtheflowers** [comment]
建议加交流群（里面除了管理都是大佬，特别是群主

**Comment by yuguangzsl** [comment]
多谢多谢

**Comment by richardchien** [comment]
这个大概因为你没有导入 `MessageSegment` 吧，close 了，如果还没解决请 reopen
