### ISSUE TITLE
发送信息失败：{'data':None,'retcode':-26,'status':'failed'}

### ISSUE THREAD

**Issue by JoffreyN** [richardchien/nonebot#90]
发送信息失败：{'data':None,'retcode':-26,'status':'failed'}，是什么原因

**Comment by richardchien** [comment]
负数的 retcode 去看 酷Q 日志

JoffreyN <notifications@github.com> 于 2019年7月26日周五 14:51写道：

**Comment by JoffreyN** [comment]
@richardchien 通过http接口调用的，没有日志

**Comment by JoffreyN** [comment]
@richardchien 谢谢，查到原因了
