### ISSUE TITLE
nonebot支持自动退出吗？

### ISSUE THREAD

**Issue by bearsmall** [richardchien/nonebot#91]
如果酷Q上登陆的账号退出了，貌似这个nonebot还是会一直监听这个端口，程序也不会退出？

**Comment by richardchien** [comment]
@bearsmall 显然 NoneBot 在运行的时候跟 酷Q 的运行状态并没有任何关系，当然不能自动退出😂。这是两个程序，应该分别控制开关。

**Comment by bearsmall** [comment]
> @bearsmall 显然 NoneBot 在运行的时候跟 酷Q 的运行状态并没有任何关系，当然不能自动退出😂。这是两个程序，应该分别控制开关。

那我能否加个心跳机制，定时和酷Q那边进行通讯（比如检测酷Q的状态），如果酷Q那边对应的账号退出了，nonebot这边至少可以知道它退出了吧？这个有没有相应的接口呢😂

**Comment by richardchien** [comment]
@bearsmall 有，你可以自己实现退出，CQHTTP 插件有个心跳包机制，用 bot.on_meta_event 可以接收，具体看下文档用法，判断多久没有收到心跳之后可以直接 exit
