### ISSUE TITLE
使用richardchien/cqhttp这个docker时好像找不到json文件了

### ISSUE THREAD

**Issue by uu9** [richardchien/nonebot#93]
但只要添加了COOLQ_ACCOUNT环境变量之后就可以在config文件下写入类似
[<user_id>]                                                                                                             
use_ws_reverse = true                                                                                                    
ws_reverse_event_url = ws://192.168.1.1:9000/ws/event/                                                                  
use_ws = true                                                                                                            
ws_reverse_api_url = ws://192.168.1.1:9000/ws/api/
希望能够在doc文件中写得更清楚一点。

**Comment by uu9** [comment]
<user_id>.ini

**Comment by richardchien** [comment]
现在 docker 容器里面，需要在 coolq/app 里面找，而不是 coolq/data/app，历史原因
