### ISSUE TITLE
docker版酷q出现301问题

### ISSUE THREAD

**Issue by liupuchun** [richardchien/nonebot#95]
日志如下：
[2019-09-17 15:56:09,647] 172.17.0.18:46591 GET /ws/api 1.1 301 183 724

docker内wine酷q设置的ip为172.17.0.1，宿主机py脚本内run的ip为0.0.0.0

**Comment by richardchien** [comment]
@liupuchun url 结尾加上 /

**Comment by liupuchun** [comment]
谢谢作者大大~！
