### ISSUE TITLE
centos使用docker版本酷Q，启动python代码失败

### ISSUE THREAD

**Issue by RowgerGo** [richardchien/nonebot#99]
酷q  docker版本
```
docker run --name=coolq -d -p 8080:9000 -v /root/coolq-data:/home/user/coolq -e VNC_PASSWD=12345678 -e COOLQ_ACCOUNT=123456 coolq/wine-coolq
```
启动酷q成功，安装http插件成功，修改json配置文件，
```
 "ws_reverse_api_url": "ws://127.0.0.1:8099/ws/api/",
   "ws_reverse_event_url": "ws://127.0.0.1:8099/ws/event/",
```
在项目bot.python文件中，
```
if __name__ == '__main__':
    nonebot.init(config)
    nonebot.load_plugins(
        path.join(path.dirname(__file__), 'awesome', 'plugins'),
        'awesome.plugins'
    )
    nonebot.run(host='127.0.0.1', port=8099)
```
使用python 3.7 启动bot.python失败，报错
 ASGI Framework Lifespan error, continuing without Lifespan suppor
查看酷q插件http日志，可以看到连接失败的正常日志输出

**Comment by RowgerGo** [comment]
我尝试着把bot监听端口8099映射到docker里面，添加 -p 8099：8099，这个时候比前面好了一点，在报错ASGI Framework Lifespan error, continuing without Lifespan suppor之后，紧接着提示Address already in use，端口被占用。问题应该是出在端口上。
第一次没有把端口映射到docker里，所以卡在了ASGI Framework Lifespan error, continuing without Lifespan suppor这一步，第二次映射进去了，继续执行下面的。但是我一时想不到好的解决方案，不映射端口，不执行下面的，映射端口了，提示端口被占用

**Comment by RowgerGo** [comment]
安装文档中配置 CoolQ HTTP API 插件那一节里面的提示，把python代码bot里地址改成0.0.0.0，然后把酷q里面http生成的json配置文件里面的地址改成服务器内网地址就运行成功了。不用再把端口映射到docker里面

**Comment by richardchien** [comment]
> -p 8099：8099

这并不能把宿主机的端口映射到容器里面，他是用来把容器里面的端口映射到宿主机的，建议仔细看下 docker 文档
